deploy:
  capistrano:
    image: fdplugins/capistrano
    when:
      branch: deploy
    commands:
      - ssh-keyscan github.com >> ~/.ssh/known_hosts
      - cap production deploy
cache:
  mount:
    - .git
    - vendor
