deploy:
  capistrano:
    image: framgia/rails
    environment:
      DATABASE_DB_NAME: cucumber_rails5_drone
      PRODUCTION_USERNAME: deploy
      SERVER_NAME: 45.32.28.225
    when:
      branch: deploy
    commands:
      - echo "DEPLOY"
      - bundle
      - cap production deploy
cache:
  mount:
    - .git
    - vendor/cache
