build:
  image: framgia/rails-workspace
  commands:
    - bundle install
    - RAILS_ENV=test rake db:create
    - RAILS_ENV=test rake db:migrate
    - rake cucumber
  environment:
    DATABASE_USERNAME_TEST: test
    DATABASE_PASSWORD_TEST: test
    DATABASE_DB_NAME_TEST: demo
    DATABASE_HOSTNAME_TEST: 127.0.0.1

compose:
  database:
    image: mysql
    environment:
      MYSQL_DATABASE: demo
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: root
deploy:
  capistrano:
    image: fdplugins/capistrano
    when:
      branch: deploy
    environment:
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: root_pass
      DATABASE_DB_NAME: cucumber_rails5
      DATABASE_HOSTNAME: localhost
      PRODUCTION_USERNAME: deploy
      SERVER_NAME: 45.32.28.225
    commands:
      - cap production deploy
cache:
  mount:
    - .git
    - vendor
